

POST  http://localhost:3001/api/blogs/5e88c9e8daf5640ff43c3bc4/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RfdXNlciIsImlkIjoiNWU4ZjU5YTc3MmFmZTkwZDdjN2MxNjllIiwiaWF0IjoxNTkwMzQxNzU1fQ._A0a81KkDbzsOs_H9drYpTR7n-bl3woUBNkRP4CDJxc

{
    "title": "Another Comment"
}
